## path
data_path: ../data/cnndm/test.jsonl
memory_path: null
output_path: null
memory_encoding: null
pretrained_model_path: ../pretrained_model/bart_large_cnn
src: document
trg: summary
## training
per_device_eval_batch_size: 2
accelerator: gpu
train_max_src_len: 512
train_max_trg_len: 80
seed: 980406
## generation
gen_max_len: 140
gen_min_len: 55
length_penalty: 2.0
diversity_penalty: 1.0
num_beam_groups: 16
num_beams: 16
num_return_sequences: 16
early_stopping: true
no_repeat_ngram_size: 3