## path
data_path: ../data/cnndm/test.jsonl
memory_path: null
output_path: null
memory_encoding: null
pretrained_model_path: null
src: document
trg: summary
## training
per_device_eval_batch_size: 12
accelerator: gpu
train_max_src_len: 1024
train_max_trg_len: 120
seed: 980406
## generation
gen_max_len: 140
gen_min_len: 55
length_penalty: 2.0
num_beams: 4
early_stopping: true
no_repeat_ngram_size: 3