# path
data_dir: ../data/cnndm
candidate_dir: null
pretrained_model_path: ../pretrained_model/roberta_large
src: document
trg: summary

accelerator: gpu
num_candidates: 16
max_length: 512
temperature: 0.05
lr: 5.0e-5
warmup_steps: 3000
weight_decay: 0.01
per_device_train_batch_size: 2
per_device_eval_batch_size: 8
logging_steps: 100
eval_metrics: rouge1
seed: 980406
accumulate_grad_batches: 8
max_epochs: 20
early_stop_patience: 5
precision: 32
enable_progress_bar: false