## path
data_dir: ../data/cnndm
pretrained_model_path: ../pretrained_model/bart_large_cnn
default_root_dir: /tmp
memory_dir: null
memory_encoding: concate
src: document
trg: summary
## training
max_epochs: 10
per_device_train_batch_size: 12
accumulate_grad_batches: 1
per_device_eval_batch_size: 12
lr: 5.0e-4
warmup_steps: 10000
accelerator: gpu
val_check_interval: 0.5
label_smoothing_factor: 0.1
gradient_clip_val: 1.0 
weight_decay: 0
train_max_src_len: 1024
train_max_trg_len: 120
logging_steps: 100
eval_metrics: rouge1
enable_progress_bar: false
seed: 980406
## generation
gen_max_len: 140
gen_min_len: 55
length_penalty: 2.0
num_beams: 4