# path
data_dir: ../data/cnndm
candidate_dir: null
pretrained_model_path: ../pretrained_model/roberta_large
src: document
trg: summary
accelerator: gpu
num_candidates: 16
max_src_len: 512
max_trg_len: 120
architecture: dual_tower
## contrastive_loss
contrastive_loss: false
temperature: 0.05
## simcls_loss
simcls_loss: true
margin: 0.01
no_gold: false
gold_weight: 1.0
gold_margin: 0.0
lr: 5.0e-3
warmup_steps: 10000
weight_decay: 0.01
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
logging_steps: 100
eval_metrics: rouge1
seed: 980406
accumulate_grad_batches: 2
max_epochs: 10
early_stop_patience: 5