data_dir: ../data/reddit
pretrained_model_path: ../pretrained_model/bart_large
default_root_dir: ../results/generator/bart_large
memory_dir: null
memory_encoding: null
src: document
trg: summary
## training
max_epochs: 10
early_stop_patience: 5
per_device_train_batch_size: 16
accumulate_grad_batches: 2
per_device_eval_batch_size: 12
lr: 3.0e-4
warmup_steps: 4000
accelerator: gpu
val_check_interval: 1.0
label_smoothing_factor: 0.1
gradient_clip_val: 1.0 
weight_decay: 0
train_max_src_len: 512
train_max_trg_len: 128
logging_steps: 100
eval_metrics: rouge1
seed: 980406
## generation
gen_max_len: 83
length_penalty: 0.6
num_beams: 5
early_stopping: true
no_repeat_ngram_size: 3