## path
data_dir: ../data/xsum
pretrained_model_path: ../pretrained_model/pegasus_xsum
default_root_dir: null
memory_dir: null
memory_encoding: concate
src: document
trg: summary
## training
max_epochs: 20
early_stop_patience: 5
per_device_train_batch_size: 16
accumulate_grad_batches: 2
per_device_eval_batch_size: 12
lr: 2.0e-3
warmup_steps: 10000
accelerator: gpu
val_check_interval: 0.5
label_smoothing_factor: 0.1
gradient_clip_val: 1.0 
weight_decay: 0
train_max_src_len: 512
train_max_trg_len: 80
logging_steps: 100
eval_metrics: rouge1
seed: 980406
## generation
gen_max_len: 64
length_penalty: 0.6
num_beams: 8
early_stopping: true
no_repeat_ngram_size: 3