## path
data_dir: ../data/samsum
candidate_dir: null
memory_dir: null
memory_encoding: null
pretrained_model_path: null
src: document
trg: summary
## training
enable_progress_bar: false
per_device_train_batch_size: 2
accumulate_grad_batches: 8
per_device_eval_batch_size: 12
lr: 2.0e-3
warmup_steps: 10000
accelerator: gpu
max_epochs: 10
val_check_interval: 0.5
label_smoothing_factor: 0.1
weight_decay: 0.01
train_max_src_len: 512
train_max_trg_len: 80
logging_steps: 100
eval_metrics: rouge1
seed: 980406
## brio
margin: 0.001
gold_margin: 0
gold_weight: 0
mle_weight: 0.1
rank_weight: 10
scale: 0.01
adding: 0.0
## generation
gen_max_len: 62
gen_min_len: 11
length_penalty: 0.6
num_beams: 8
