# path
data_dir: ../data/xsum
candidate_dir: null
pretrained_model_path: ../pretrained_model/deberta_v3_large
src: document
trg: summary
enable_progress_bar: false
accelerator: gpu
num_candidates: 16
max_length: 512
temperature: 0.05
lr: 5.0e-3
warmup_steps: 5000
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
logging_steps: 100
eval_metrics: rouge1
seed: 980406
accumulate_grad_batches: 8
max_epochs: 10
early_stop_patience: 5
precision: 16