## path
data_dir: ../data/samsum
pretrained_model_path: ../pretrained_model/bart_large
default_root_dir: ../results/finetune_samsum
memory_dir: null
memory_encoding: concate
src: document
trg: summary
## training
per_device_train_batch_size: 8
accumulate_grad_batches: 4
per_device_eval_batch_size: 12
lr: 5.0e-3
warmup_steps: 4000
accelerator: gpu
max_epochs: 10
val_check_interval: 0.5
label_smoothing_factor: 0.1
gradient_clip_val: 1.0 
weight_decay: 0
train_max_src_len: 512
train_max_trg_len: 80
logging_steps: 100
eval_metrics: rouge1
seed: 980406
## generation
gen_max_len: 69
gen_min_len: 9
num_beams: 5
no_repeat_ngram_size: 3
early_stopping: true
num_beam_groups: 1
length_penalty: 1.0 
diversity_penalty: 0.0
