## path
data_dir: ../data/samsum
candidate_dir: null
memory_dir: null
memory_encoding: null
pretrained_model_path: null
src: document
trg: summary
## training
per_device_train_batch_size: 1
accumulate_grad_batches: 32
per_device_eval_batch_size: 12
lr: 5.0e-3
warmup_steps: 10000
accelerator: gpu
max_epochs: 10
val_check_interval: 0.5
label_smoothing_factor: 0.1
weight_decay: 0.01
train_max_src_len: 512
train_max_trg_len: 80
logging_steps: 100
eval_metrics: rouge1
seed: 980406
## brio
margin: 0.001
gold_margin: 0
gold_weight: 0
mle_weight: 0.1
rank_weight: 10
scale: 0.01
adding: 0.0
## generation
gen_max_len: 69
gen_min_len: 9
num_beams: 5
no_repeat_ngram_size: 3
early_stopping: true
length_penalty: 1.0
num_return_sequences: 1
