## path
data_path: null
memory_path: null
output_path: null
memory_encoding: null
pretrained_model_path: null
src: document
trg: summary
## training
per_device_eval_batch_size: 2
accelerator: gpu
train_max_src_len: 1024
train_max_trg_len: 256
seed: 980406
## generation
gen_max_len: 256
gen_min_len: 34
length_penalty: 0.7
diversity_penalty: 1.0
num_beam_groups: 16
num_beams: 16
num_return_sequences: 16
early_stopping: true